### ISSUE TITLE
Source for Prebuilt Qt5 binaries 

### ISSUE THREAD

**Issue by ycheng** [penk/oxide-eglfs-snap#1]
Source for Prebuilt Qt5 binaries and how we can extend it (to different platform)

**Comment by penk** [comment]
We can use stage packages `libqt5gui5-gles`, `libqt5opengl5-gles` and `libqt5quick5-gles` for Qt5, but `liboxideqt-qmlplugin` needs to be rebuilt and linked against OpenGL ES anyway.
